services:
  heroes_db:
    image: 'postgres'
    volumes:
      - heroes_data:/var/lib/postgresql/data
    env_file:
      - ./secrets.env
    ports:
      - "5432:5432"
    container_name: "heroes_db"

  heroes_app:
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - heroes_db
    container_name: "heroes_app"
    environment:
      - secrets.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  heroes_data:

